2023-11-15 19:47:23,439 INFO    StreamThr :33805 [internal.py:wandb_internal():86] W&B internal server running at pid: 33805, started at: 2023-11-15 19:47:23.427288
2023-11-15 19:47:23,442 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status
2023-11-15 19:47:23,484 INFO    WriterThread:33805 [datastore.py:open_for_write():85] open: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/run-sjr60a97.wandb
2023-11-15 19:47:23,497 DEBUG   SenderThread:33805 [sender.py:send():380] send: header
2023-11-15 19:47:23,872 DEBUG   SenderThread:33805 [sender.py:send():380] send: run
2023-11-15 19:47:24,425 INFO    SenderThread:33805 [dir_watcher.py:__init__():211] watching files in: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files
2023-11-15 19:47:24,425 INFO    SenderThread:33805 [sender.py:_start_run_threads():1122] run started: sjr60a97 with start time 1700074043.478829
2023-11-15 19:47:24,516 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: check_version
2023-11-15 19:47:24,517 DEBUG   SenderThread:33805 [sender.py:send_request():407] send_request: check_version
2023-11-15 19:47:24,624 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: run_start
2023-11-15 19:47:24,654 DEBUG   HandlerThread:33805 [system_info.py:__init__():32] System info init
2023-11-15 19:47:24,654 DEBUG   HandlerThread:33805 [system_info.py:__init__():47] System info init done
2023-11-15 19:47:24,654 INFO    HandlerThread:33805 [system_monitor.py:start():194] Starting system monitor
2023-11-15 19:47:24,655 INFO    SystemMonitor:33805 [system_monitor.py:_start():158] Starting system asset monitoring threads
2023-11-15 19:47:24,655 INFO    HandlerThread:33805 [system_monitor.py:probe():214] Collecting system info
2023-11-15 19:47:24,656 INFO    SystemMonitor:33805 [interfaces.py:start():190] Started cpu monitoring
2023-11-15 19:47:24,657 INFO    SystemMonitor:33805 [interfaces.py:start():190] Started disk monitoring
2023-11-15 19:47:24,659 INFO    SystemMonitor:33805 [interfaces.py:start():190] Started gpu monitoring
2023-11-15 19:47:24,660 INFO    SystemMonitor:33805 [interfaces.py:start():190] Started memory monitoring
2023-11-15 19:47:24,661 INFO    SystemMonitor:33805 [interfaces.py:start():190] Started network monitoring
2023-11-15 19:47:24,712 DEBUG   HandlerThread:33805 [system_info.py:probe():196] Probing system
2023-11-15 19:47:24,743 DEBUG   HandlerThread:33805 [system_info.py:_probe_git():181] Probing git
2023-11-15 19:47:25,008 DEBUG   HandlerThread:33805 [system_info.py:_probe_git():189] Probing git done
2023-11-15 19:47:25,009 DEBUG   HandlerThread:33805 [system_info.py:probe():244] Probing system done
2023-11-15 19:47:25,009 DEBUG   HandlerThread:33805 [system_monitor.py:probe():223] {'os': 'Linux-3.10.0-1160.95.1.el7.x86_64-x86_64-with-glibc2.17', 'python': '3.9.16', 'heartbeatAt': '2023-11-15T18:47:24.712574', 'startedAt': '2023-11-15T18:47:23.244413', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/./run.py', 'codePathLocal': 'run.py', 'codePath': 'DKT/KnowledgeTracing/evaluation/run.py', 'git': {'remote': 'https://github.com/Bryanttt-tang/Deep-Knowledge-Tracing.git', 'commit': 'f5d964306cebcbfcdb1e181135e8ab92caeaca6e'}, 'email': 'tangyu990628@gmail.com', 'root': '/cluster/home/yutang/Deep-Knowledge-Tracing', 'host': 'eu-lo-dgx1-001', 'username': 'yutang', 'executable': '/cluster/home/yutang/miniconda3/bin/python', 'cpu_count': 40, 'cpu_count_logical': 80, 'cpu_freq': {'current': 1616.5644250000003, 'min': 1200.0, 'max': 3600.0}, 'cpu_freq_per_core': [{'current': 3287.915, 'min': 1200.0, 'max': 3600.0}, {'current': 3309.936, 'min': 1200.0, 'max': 3600.0}, {'current': 1201.245, 'min': 1200.0, 'max': 3600.0}, {'current': 1297.119, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.036, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.17, 'min': 1200.0, 'max': 3600.0}, {'current': 1231.726, 'min': 1200.0, 'max': 3600.0}, {'current': 1222.326, 'min': 1200.0, 'max': 3600.0}, {'current': 1214.538, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.439, 'min': 1200.0, 'max': 3600.0}, {'current': 1328.137, 'min': 1200.0, 'max': 3600.0}, {'current': 3256.091, 'min': 1200.0, 'max': 3600.0}, {'current': 1693.908, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.439, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.708, 'min': 1200.0, 'max': 3600.0}, {'current': 1216.149, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.17, 'min': 1200.0, 'max': 3600.0}, {'current': 1299.536, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.305, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.573, 'min': 1200.0, 'max': 3600.0}, {'current': 3036.279, 'min': 1200.0, 'max': 3600.0}, {'current': 1242.602, 'min': 1200.0, 'max': 3600.0}, {'current': 1201.379, 'min': 1200.0, 'max': 3600.0}, {'current': 1299.67, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.305, 'min': 1200.0, 'max': 3600.0}, {'current': 3042.59, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.17, 'min': 1200.0, 'max': 3600.0}, {'current': 2991.43, 'min': 1200.0, 'max': 3600.0}, {'current': 3014.929, 'min': 1200.0, 'max': 3600.0}, {'current': 1218.969, 'min': 1200.0, 'max': 3600.0}, {'current': 3034.936, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.708, 'min': 1200.0, 'max': 3600.0}, {'current': 1211.987, 'min': 1200.0, 'max': 3600.0}, {'current': 1898.278, 'min': 1200.0, 'max': 3600.0}, {'current': 1299.133, 'min': 1200.0, 'max': 3600.0}, {'current': 1261.669, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.17, 'min': 1200.0, 'max': 3600.0}, {'current': 1201.513, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.439, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.305, 'min': 1200.0, 'max': 3600.0}, {'current': 3273.144, 'min': 1200.0, 'max': 3600.0}, {'current': 3321.215, 'min': 1200.0, 'max': 3600.0}, {'current': 1294.03, 'min': 1200.0, 'max': 3600.0}, {'current': 1276.574, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.439, 'min': 1200.0, 'max': 3600.0}, {'current': 1251.599, 'min': 1200.0, 'max': 3600.0}, {'current': 1286.645, 'min': 1200.0, 'max': 3600.0}, {'current': 1258.178, 'min': 1200.0, 'max': 3600.0}, {'current': 1204.467, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.17, 'min': 1200.0, 'max': 3600.0}, {'current': 1299.938, 'min': 1200.0, 'max': 3600.0}, {'current': 2735.363, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.036, 'min': 1200.0, 'max': 3600.0}, {'current': 1204.736, 'min': 1200.0, 'max': 3600.0}, {'current': 1226.489, 'min': 1200.0, 'max': 3600.0}, {'current': 1215.612, 'min': 1200.0, 'max': 3600.0}, {'current': 1209.033, 'min': 1200.0, 'max': 3600.0}, {'current': 1224.609, 'min': 1200.0, 'max': 3600.0}, {'current': 1206.884, 'min': 1200.0, 'max': 3600.0}, {'current': 1218.432, 'min': 1200.0, 'max': 3600.0}, {'current': 2879.711, 'min': 1200.0, 'max': 3600.0}, {'current': 1207.287, 'min': 1200.0, 'max': 3600.0}, {'current': 1204.333, 'min': 1200.0, 'max': 3600.0}, {'current': 1924.731, 'min': 1200.0, 'max': 3600.0}, {'current': 1208.63, 'min': 1200.0, 'max': 3600.0}, {'current': 3075.354, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.573, 'min': 1200.0, 'max': 3600.0}, {'current': 3153.637, 'min': 1200.0, 'max': 3600.0}, {'current': 3039.501, 'min': 1200.0, 'max': 3600.0}, {'current': 1213.061, 'min': 1200.0, 'max': 3600.0}, {'current': 2706.494, 'min': 1200.0, 'max': 3600.0}, {'current': 1201.513, 'min': 1200.0, 'max': 3600.0}, {'current': 1203.393, 'min': 1200.0, 'max': 3600.0}, {'current': 1691.894, 'min': 1200.0, 'max': 3600.0}, {'current': 1229.309, 'min': 1200.0, 'max': 3600.0}, {'current': 1299.938, 'min': 1200.0, 'max': 3600.0}, {'current': 1201.513, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.036, 'min': 1200.0, 'max': 3600.0}, {'current': 1204.87, 'min': 1200.0, 'max': 3600.0}, {'current': 1200.708, 'min': 1200.0, 'max': 3600.0}], 'disk': {'/': {'total': 10.0, 'used': 4.597599029541016}}, 'gpu': 'Tesla V100-SXM2-32GB', 'gpu_count': 1, 'gpu_devices': [{'name': 'Tesla V100-SXM2-32GB', 'memory_total': 34359738368}], 'memory': {'total': 501.5517120361328}}
2023-11-15 19:47:25,009 INFO    HandlerThread:33805 [system_monitor.py:probe():224] Finished collecting system info
2023-11-15 19:47:25,009 INFO    HandlerThread:33805 [system_monitor.py:probe():227] Publishing system info
2023-11-15 19:47:25,009 DEBUG   HandlerThread:33805 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-11-15 19:47:25,027 DEBUG   HandlerThread:33805 [system_info.py:_save_pip():68] Saving pip packages done
2023-11-15 19:47:25,033 DEBUG   HandlerThread:33805 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-11-15 19:47:25,441 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/requirements.txt
2023-11-15 19:47:25,441 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/conda-environment.yaml
2023-11-15 19:47:59,720 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/conda-environment.yaml
2023-11-15 19:47:59,732 DEBUG   HandlerThread:33805 [system_info.py:_save_conda():87] Saving conda packages done
2023-11-15 19:47:59,751 INFO    HandlerThread:33805 [system_monitor.py:probe():229] Finished publishing system info
2023-11-15 19:47:59,874 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:47:59,874 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: keepalive
2023-11-15 19:47:59,874 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:47:59,875 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: keepalive
2023-11-15 19:47:59,875 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:47:59,875 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: keepalive
2023-11-15 19:47:59,875 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:47:59,875 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: keepalive
2023-11-15 19:47:59,875 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:47:59,875 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: keepalive
2023-11-15 19:47:59,875 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:47:59,875 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: stop_status
2023-11-15 19:47:59,875 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: internal_messages
2023-11-15 19:47:59,875 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:47:59,875 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: keepalive
2023-11-15 19:47:59,877 DEBUG   SenderThread:33805 [sender.py:send_request():407] send_request: stop_status
2023-11-15 19:48:00,084 DEBUG   SenderThread:33805 [sender.py:send():380] send: telemetry
2023-11-15 19:48:00,098 DEBUG   SenderThread:33805 [sender.py:send():380] send: files
2023-11-15 19:48:00,098 INFO    SenderThread:33805 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-11-15 19:48:00,416 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7ea6566fd0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-15 19:48:00,417 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9939'}
2023-11-15 19:48:00,417 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-15 19:48:00,733 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/wandb-metadata.json
2023-11-15 19:48:00,734 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:01,575 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7ea52ee550>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-15 19:48:01,576 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9939'}
2023-11-15 19:48:01,576 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-15 19:48:02,769 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:04,047 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7ea6566700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-15 19:48:04,047 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9939'}
2023-11-15 19:48:04,047 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-15 19:48:04,047 INFO    wandb-upload_0:33805 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x2b7ea6566700>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7ea6566700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7ea6566700>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2580, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2549, in upload_file
    response = self._upload_file_session.put(
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-11-15 19:48:04,099 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:48:08,372 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7ea52ee790>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-15 19:48:08,378 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9939'}
2023-11-15 19:48:08,378 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-15 19:48:09,451 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:48:09,697 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: keepalive
2023-11-15 19:48:09,698 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: stop_status
2023-11-15 19:48:09,698 DEBUG   SenderThread:33805 [sender.py:send_request():407] send_request: stop_status
2023-11-15 19:48:10,852 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:12,871 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:14,889 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:14,994 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:48:16,907 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:17,675 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7ef4686670>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-15 19:48:17,676 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9939'}
2023-11-15 19:48:17,676 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-15 19:48:18,920 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:20,277 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:48:22,967 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:24,662 DEBUG   SystemMonitor:33805 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2023-11-15 19:48:24,666 DEBUG   SenderThread:33805 [sender.py:send():380] send: stats
2023-11-15 19:48:24,698 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: keepalive
2023-11-15 19:48:24,698 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: stop_status
2023-11-15 19:48:24,699 DEBUG   SenderThread:33805 [sender.py:send_request():407] send_request: stop_status
2023-11-15 19:48:25,587 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:48:26,019 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/config.yaml
2023-11-15 19:48:27,031 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:31,073 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:31,280 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:48:35,120 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:36,109 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7ef46867f0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-15 19:48:36,109 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9939'}
2023-11-15 19:48:36,109 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-15 19:48:36,649 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:48:39,162 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:39,698 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: keepalive
2023-11-15 19:48:39,699 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: stop_status
2023-11-15 19:48:39,699 DEBUG   SenderThread:33805 [sender.py:send_request():407] send_request: stop_status
2023-11-15 19:48:41,175 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:42,325 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:48:45,211 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:47,684 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:48:49,265 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:51,283 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:52,763 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:48:54,668 DEBUG   SenderThread:33805 [sender.py:send():380] send: stats
2023-11-15 19:48:54,698 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: keepalive
2023-11-15 19:48:54,707 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: keepalive
2023-11-15 19:48:54,708 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: stop_status
2023-11-15 19:48:54,708 DEBUG   SenderThread:33805 [sender.py:send_request():407] send_request: stop_status
2023-11-15 19:48:55,331 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:57,349 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:48:57,826 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:49:01,386 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:49:03,091 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:49:03,415 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:49:07,452 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:49:08,197 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
2023-11-15 19:49:09,470 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:49:09,699 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: keepalive
2023-11-15 19:49:09,699 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: stop_status
2023-11-15 19:49:09,700 DEBUG   SenderThread:33805 [sender.py:send_request():407] send_request: stop_status
2023-11-15 19:49:10,176 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2556] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/bryant-ty/DKT-trial%201/sjr60a97/wandb-metadata.json?Expires=1700160480&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ijMqVWfzJ0cAKd7ppLqsQFbxd85c6T9hr8EwlzS26Ow9RHewmVfwzU95CmpGtgqp0LOf%2BsNSqVKMCeWYik4K%2BbBNPKvIdPFE85jHg%2FLo6qJQZ8DP3UpI4rKPR%2BNPOaQ8%2Fgq0M3nrMh3nMz3LTYSABlsrsoDERQ9URoPBPjltievPdaWu8sYcccO0y4B%2BjPGTZCbEPtImt%2F45hgm1dgEivObbMsnL5OC4GQi0HMpeRRCFoChCrcH7r3NbSRvhQL54jVTJf7w6rZIdRHshbr0mBAXHRHjRYrjhAkbxjyMBZutLI4zt0ccqDXjJBNntX5IJ0ZAWabQD%2BF5nLAid9Rq19A%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2b7ef468f310>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
2023-11-15 19:49:10,176 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2558] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '9939'}
2023-11-15 19:49:10,176 ERROR   wandb-upload_0:33805 [internal_api.py:upload_file():2560] upload_file response body: 
2023-11-15 19:49:13,512 INFO    Thread-12 :33805 [dir_watcher.py:_on_file_modified():288] file/dir modified: /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231115_194723-sjr60a97/files/output.log
2023-11-15 19:49:13,641 DEBUG   HandlerThread:33805 [handler.py:handle_request():146] handle_request: status_report
