
Dataset: LON_course4, Learning Rate: 0.002
loading train data:    : 693it [00:01, 538.00it/s]
loading test data:    : 167it [00:00, 1504.02it/s]
Training:    :   0%|                                                                                                       | 0/109 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "d:/ETHz/Internship/adaptive-e-learning-for-educational-recommendation-system/DeepKnowledgeTracing-DKT-Pytorch/DKT/KnowledgeTracing/evaluation/run.py", line 45, in <module>
    model, optimizer, train_loss = eval.train(trainLoaders, model, optimizer_adgd, loss_func,device)
  File "D:\ETHz\Internship\adaptive-e-learning-for-educational-recommendation-system\DeepKnowledgeTracing-DKT-Pytorch\DKT\KnowledgeTracing\evaluation\eval.py", line 100, in train
    model, optimizer, train_loss = train_epoch(model, trainLoaders[i], optimizer, lossFunc,device)
  File "D:\ETHz\Internship\adaptive-e-learning-for-educational-recommendation-system\DeepKnowledgeTracing-DKT-Pytorch\DKT\KnowledgeTracing\evaluation\eval.py", line 49, in train_epoch
    for batch in tqdm.tqdm(trainLoader, desc='Training:    ', mininterval=2):
  File "C:\Users\tyu06\anaconda3\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\tyu06\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 530, in __next__
    data = self._next_data()
  File "C:\Users\tyu06\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 570, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\tyu06\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\tyu06\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\ETHz\Internship\adaptive-e-learning-for-educational-recommendation-system\DeepKnowledgeTracing-DKT-Pytorch\DKT\KnowledgeTracing\data\DKTDataSet.py", line 17, in __getitem__
    onehot = self.onehot(questions, answers)
  File "D:\ETHz\Internship\adaptive-e-learning-for-educational-recommendation-system\DeepKnowledgeTracing-DKT-Pytorch\DKT\KnowledgeTracing\data\DKTDataSet.py", line 26, in onehot
    result[i][questions[i] + C.NUM_OF_QUESTIONS] = 1
IndexError: index 342 is out of bounds for axis 0 with size 322
epoch: 0