loading train data:    : 693it [00:00, 1133.36it/s]
loading test data:    : 167it [00:00, 1813.36it/s]
Training:    :   0%|          | 0/32 [00:00<?, ?it/s]































Training:    : 100%|██████████| 32/32 [01:48<00:00,  3.41s/it]
Testing:    :   0%|          | 0/32 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/./run.py", line 60, in <module>
    train_auc, train_f1, train_recall, train_precision,train_loss=eval.test(trainLoaders, model,loss_func, device)
  File "/cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/eval.py", line 109, in test
    pred_epoch, gold_epoch, val_loss = test_epoch(model, testLoaders[i],loss_func,device)
  File "/cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/eval.py", line 81, in test_epoch
    delta = batch[student][:,0:C.NUM_OF_QUESTIONS] + batch[student][:,C.NUM_OF_QUESTIONS:]
RuntimeError: The size of tensor a (227) must match the size of tensor b (228) at non-singleton dimension 1