2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_setup.py:_flush():76] Configure stats pid to 25571
2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_setup.py:_flush():76] Loading settings from /cluster/home/yutang/.config/wandb/settings
2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_setup.py:_flush():76] Loading settings from /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/settings
2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'DKT/KnowledgeTracing/evaluation/run.py', 'program_abspath': '/cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/run.py', 'program': '/cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/./run.py'}
2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_init.py:_log_setup():524] Logging user logs to /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231225_175359-3lttqxxf/logs/debug.log
2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_init.py:_log_setup():525] Logging internal logs to /cluster/home/yutang/Deep-Knowledge-Tracing/DKT/KnowledgeTracing/evaluation/wandb/run-20231225_175359-3lttqxxf/logs/debug-internal.log
2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_init.py:init():564] calling init triggers
2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_init.py:init():614] starting backend
2023-12-25 17:53:59,596 INFO    MainThread:25571 [wandb_init.py:init():618] setting up manager
2023-12-25 17:53:59,598 INFO    MainThread:25571 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-12-25 17:53:59,601 INFO    MainThread:25571 [wandb_init.py:init():624] backend started and connected
2023-12-25 17:53:59,607 INFO    MainThread:25571 [wandb_init.py:init():716] updated telemetry
2023-12-25 17:53:59,631 INFO    MainThread:25571 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-25 17:54:00,704 WARNING MsgRouterThr:25571 [router.py:message_loop():77] message_loop has been closed
2023-12-25 17:54:09,682 ERROR   MainThread:25571 [wandb_init.py:init():1188] transport failed
Traceback (most recent call last):
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 752, in init
    result = run_init_handle.wait(
  File "/cluster/home/yutang/miniconda3/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
